### PR TITLE
reverted changes and moved functionality to only the scanner command

### PR DESCRIPTION
**Pull request by adaviloper**
## Description

Existing features are now editable again.

## Motivation and context

Original PR made it so that existing features could not be toggled.

## How has this been tested?

Instead of passing all found features, we now only pass in scanned features that are not enabled.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [ ] I have added tests to cover my changes.
- [ ] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by ivannovak** [comment]
What led to this change?

**Comment by adaviloper** [comment]
@ivannovak The original PR affected the `save` method in the `EloquentFeatureRepository` class. This class is shared for its functionality for enabling and disabling features. With my original change, the model's current `is_enabled` status would override any status update that was being sent in to the `save` method, meaning that no feature's status would be able to be updated.

So, instead, I opted to have it only pass in features that are not enabled to be passed to the `save` method.

**Review by ivannovak — APPROVED** [review]
LGTM

**Comment by adaviloper** [comment]
Would it perhaps be better with this change?

```
if ($this->featureManager->isEnabled($directive) === $this->config->get('features.scanned_default_enabled')) {
    $this->featureManager->add($directive, $this->config->get('features.scanned_default_enabled'));
 }
```

**Comment by ivannovak** [comment]
If it were me, I'd probably add an `exists` method and check against that instead of inferring the existence through `isEnabled` which may be accurate on occasion and inaccurate in others.

**Comment by adaviloper** [comment]
Added.

**Review by ivannovak — APPROVED** [review]

**Comment by abodnar** [comment]
I approve.

**Pull request merged**
